--- # Test playbook for LOOPS..
- hosts: local
  user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  
  tasks:
  - name: Creating Users using LOOP
    user: name={{ item }} state=present
    with_items:
         - user4
         - user5
         - user6
